# Generated by Django 3.2.25 on 2025-07-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoughType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('extra_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dough Type',
                'verbose_name_plural': 'Dough Types',
                'ordering': ['name'],
            },
        ),
    ]
