# Generated by Django 3.2.25 on 2025-07-26 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eshop_app', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Preparing Food', 'Preparing Food'), ('Ready for Pickup', 'Ready for Pickup'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Created', max_length=50)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_without_vat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eshop_app.paymenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item_name_at_order', models.CharField(max_length=255)),
                ('dough_type_name_at_order', models.CharField(max_length=100)),
                ('unit_price_at_order', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('dough_type_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eshop_app.doughtype')),
                ('menu_item_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eshop_app.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='eshop_app.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
